### ISSUE TITLE
Auto-update / self-update binaries

### ISSUE THREAD

**Issue by joepio** [joepio/atomic-data-rust#158]
Ideally, atomic-server could update itself - without any CLI activity.

~~The [`self_update` crate](https://docs.rs/self_update) seems pretty nice.~~

We'll use Tauri for the desktop distro.

Issue on tauri to make this even easier: https://github.com/tauri-apps/tauri-action/issues/251

**Comment by joepio** [comment]
When should auto update be initialized? I think we should check (every 24 hours maybe) for new versions, and if one is found, signal the manager of the server somehow. Applying the update automatically might be a reasonable thing for some users, but for others it is too much of a risk. If anything goes wrong in a version update, the user will not be aware of this until some time later. In some situation, stability is far more important than running the latest version.

Maybe add an `/update` endpoint that requires a signed request from the `default_agent`? However, that would mean that if a user signs up using the `/setup` invite, they would not be allowed to update the server... Maybe check if the user has write rights on the `base_url`?

**Comment by joepio** [comment]
I'm planning on implementing this by using Tauri #215

**Comment by jonassmedegaard** [comment]
please provide a compile-time option to disable automatic updates: some distributions (including Debian) forbid non-package-management changes below /usr/bin and /usr/lib and /usr/share - and it is pretty awkward to have to install atomic-data below /usr/var

**Comment by joepio** [comment]
Good point. The Tauri build will be a separate build from the regular server one. It will have desktop features, a GUI, and self-update. I'll keep supporting the regular `atomic-server` build, which will not have an automatic update.

**Comment by jonassmedegaard** [comment]
excellent!

**Comment by joepio** [comment]
Will probably be fixed by #221

**Comment by joepio** [comment]
This iroh-based tool is pretty interesting: https://github.com/rustonbsd/rustpatcher
