### ISSUE TITLE
Failed running GLIC missing when running docker

### ISSUE THREAD

**Issue by tsaltena** [joepio/atomic-data-rust#186]
/server/atomic-server-bin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /server/atomic-server-bin)

**Comment by joepio** [comment]
It's working again! `docker pull joepmeneer/atomic-server:latest` + `docker run -p 80:80 -p 443:443 -v atomic-storage:/atomic-storage joepmeneer/atomic-server:latest`
