### ISSUE TITLE
atomic-server --help output is insufficient

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#187]
Please extend the output of `atomic-server --help` to add new section `ENVIRONMENT` containing the contents of `server/default.env`.
And consider improving that to be descriptive for all entries - notably replace this with whatever it implies:
> Set this to true during development

(this issues relates to the more elaborate issue #154).

**Comment by joepio** [comment]
Good suggestions! Thanks

**Comment by jonassmedegaard** [comment]
I am **very** new to Rust, so please don't mock me too much if this is way off:
Seems a compact and DRY approach if you don't mind depending on rust version 1.54.0 is to use [include_str](https://doc.rust-lang.org/std/macro.include_str.html).

**Comment by joepio** [comment]
That is a great macro for thing like this. I'm thinking maybe it would be easiest if there was a separate command for creating the `.env` in your current directory. What do you think?

**Comment by jonassmedegaard** [comment]
Sorry, I am clueless - I haven't even written a hello World yet in rust, only built some projects and patched them a bit to fit Debian - which is where I came across [this](https://github.com/gtk-rs/gtk4-rs/blob/98cbe2620afd081dec774e43c01114635f3af459/gdk4/src/lib.rs#L7) and [this](https://gitlab.freedesktop.org/ryuukyu/helvum/-/blob/main/meson.build#L16) (because at the time Debian had a slightly too old Rustc so I needed to patch that).

**Comment by jonassmedegaard** [comment]
Ohh, I think I misunderstood your question.
This issue is not about _changing_ any functionality but only about enhancing the output of the `--help` option to cover other aspects of configuration than options.

**Comment by joepio** [comment]
Got it, I'll make sure the `--help` will at least allow you to discover the `.env` settings. I do think the `default.env` output would be easy, though, so I'll introduce that too.

**Comment by joepio** [comment]
I've added a `setup-env` command which gives all the setup options
