### ISSUE TITLE
better to fail startup than auto-kill other running instances

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#324]
I stumbled upon #167 and that sems bad design to me: Normal behavior of daemons is to simply refuse to start if a pidfile exist and the referenced PID is alive.

It seems you wanted the forceful startup specifically for certain deployment scripts.  I urge you to consider *removing* this functionality from atomic-server and instead handle such unusual forceful treatment of pre-existing processes e.g. by having your deployment script do a `killall atomic-server && sleep 2 || true` before starting atomic-server.

Reason I stumbled upon #167 was that I wondered why `heim` was used.  If you insist that forceful startup should be implemented in atomic-server itself, then at least consider moving to a more lightweight library for that - e.g. `sysinfo`.  I have zero experience programming in Rust, so only mention that alternative because others seem to recommend it, both at [stackoverflow](https://stackoverflow.com/a/70818623) and [users.rust-lang.org](https://users.rust-lang.org/t/getprocessid-by-name-in-rust/46056).

**Comment by jonassmedegaard** [comment]
Here is an excellent explanation on why it is better to leave daemon handling to external tools: https://stackoverflow.com/a/61681452

I.e. the recommendation there goes even further: Don't create a PID file at all - leave that to external tools as well!

**Comment by jonassmedegaard** [comment]
> If you [try to handle daemonizing yourself, and do it wrong], the process becomes kind of hard to find and kill.

Yes, handling background processes correctly is hard. Very hard. Might even be insecure - depending on how you fail to do it exactly correct.

So don't do it yourself.

Just please pretty please don't do it yourself.

**Comment by joepio** [comment]
Ok, no real arguments still, but I know that I can trust your opinion on this. I'll remove the feature.
