### ISSUE TITLE
config dir is (ab)used for storage and cache

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#331]
Option `--config-dir` or environment variable `ATOMIC_CONFIG_DIR` is used not only for configuration but also for ephemeral and precious data.

Please align with FreeDesktop [Base Directory Specification](https://en.wikipedia.org/wiki/Freedesktop.org#Base_Directory_Specification), distinguishing between...

 * Precious data
   * potentially large
   * candidate for privacy-protected backup routines
 * Configuration data
   * typically lightweight
   * candidate for less privacy-oriented backup routines
   * often reasonable to reuse unedited across systems.
 * Ephemeral cheap data like cache files
   * potentially large (but might support auto-dropping older entries to save space)
   * candidate for storing on extra-fast storage (e.g. SSD, or in special cases a RAM disk)
 * Ephemeral expensive data like database indexes
   * potentially large (but might support auto-dropping older entries to save space)
   * might requiring downtime or locks to create
   * candidate for storing on extra-fast storage (e.g. SSD, or in special cases a RAM disk)
  * execution-specific data
    * typically lightweight
    * might require root access to create and clean up

Concretely, I suggest these paths:
  * config.toml -> $XDG_CONFIG_DIRS/atomic-data/server.toml
  * trace-*.json -> $XDG_LOG_DIRS/atomic-data/server/trace-*.json
  * atomic_server_process_id -> $XDG_RUNTIME_DIRS/atomic-data/server_process_id
  * db/* -> $XDG_DATA_DIRS/atomic-data/server/db/*
  * search_index/* -> $XDG_STATE_DIRS/atomic-data/server/search_index/*

Seems [directories](https://crates.io/crates/directories) is the perfect library for this.

**Comment by jonassmedegaard** [comment]
I updated above suggested paths to use subdir server/ for both DATA_DIR and STATE_DIR, since those subdirs might require restricted access even from "friendly" users (e.g. related atomic-data tools might be permitted read-only access but not write access).

**Comment by joepio** [comment]
Yeah, I always though I was kind of making a mess with the directories. It simply seemed like a good UX to have everything in one folder, but XDG BDS exists for good reason.

**Comment by jonassmedegaard** [comment]
Seems the crate to use for this is [directories](https://crates.io/crates/directories) - and please relax dependency to ">= 2, < 5" and only fixate to newer version using `Cargo.lock` as downstream ABI is same and older releases work fine for linux.

**Comment by jonassmedegaard** [comment]
...and on a related note, current dependency on crate `dirs` can be relaxed to ">= 2, < 5" for the same reason.

**Comment by joepio** [comment]
Seems like `dirs` and `directories` have very similar scope. The one I'm currently using, `dirs`, also uses `XDG`. Do you see any reason to switch?

**Comment by jonassmedegaard** [comment]
They are documented as "sister" libraries, and the answer is likely found in their `Design Goals" sections.  E.g. this passage in `Design Goals` of `dirs`:
> If your requirements are more complex, e. g. computing cache, config, etc. paths for specific applications or projects, consider using [directories](https://github.com/dirs-dev/directories-rs) instead.

**Comment by jonassmedegaard** [comment]
...or the `Comparison` section :-D
