### ISSUE TITLE
distinguish start-the-service from service-specific tools

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#334]
The command-line application `atomic-server` is mainly a daemon: When executed without options, it opens a port for an Atomic Server, without exiting to the shell.

Samme application also contains service house-keeping functionalities, e.g. to reset admin password.
It is confusing, however, that `atomic-server --initialize` does not *only* do what is documented but *also* starts a daemon.
My expectation is that when requesting a functional option then that function is executed *instead* of the default of running as a service.
An alternative (and [my earlier expectation](https://github.com/ontola/atomic-data-docs/issues/110#issuecomment-1070771844)) would be to provide a separate command-line for non-service-starting functions.

Or rephrased: Seems impossible to e.g. reset password **without** starting service.

**Comment by jonassmedegaard** [comment]
See [here](https://salsa.debian.org/debian/atomic-data-rust/-/blob/debian/latest/debian/README.Debian) for a concrete example of how cludgy the current interface becomes.

...or maybe I am simply missing some elegant different usage pattern?

**Comment by joepio** [comment]
Hmm, I see your point. If `--initialize` is changed with `initialize`, and it quits after performing the initialization, would that suffice? You'd still need to shut off the service, though, I need to run the script when actually initializing the server.

It would probably become:
 
```
    sudo service atomic-server stop
    sudo -u _atomic atomic-server initialize
    sudo service atomic-server start
```

Is that a significant improvement?
