### ISSUE TITLE
source path server/static contains templates (not static assets)

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#353]
Source path `source/static` does not contain files used as-is, but instead template files.  I suggest renaming that directory e.g. to `templates`.

Very minor issue, sorry - it was just that I wondered about that several times browsing through the source code, and therefore decided to share it with you.  Feel free to close without explanation...

**Comment by joepio** [comment]
True, the name is no longer fitting. Thanks for the suggestion, fixed it.
