### ISSUE TITLE
unclear if option --public-mode relax write or only read

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#354]
Description for option `--public-mode` warns that it is "making  all  data  public" - but technically that can mean either public *readable* or public *writable*, and which of those two meanings apply is unclear from current wording.

**Comment by jonassmedegaard** [comment]
Similar for option `--rdf-search` but less severe, as it is kinda implied (but not certain) that only that detailed documented `POST` command i public, which is documented as being a read-only command.

**Comment by joepio** [comment]
Agreed, fixed!
