### ISSUE TITLE
links with two versions of clap

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#358]
atomic-cli uses clap v2.33.3 and atomic-server uses clap v3.0.0-rc.3.

I guess there's at least a size benefit, but likely also a quality improvement, in modernizing both to use v3.0.0 (which allows to link against newest v3.1.6 for both).

**Comment by joepio** [comment]
Hmm, looks like I updated clap about one month ago.  I guess you were looking at the latest tagged release, not the main branch?

https://github.com/joepio/atomic-data-rust/commit/0800e340b56d14b3cecaa035a456a86ccca83b5c

**Comment by jonassmedegaard** [comment]
Quoting Joep Meindertsma (2022-03-28 21:43:14)
> Hmm, looks like I updated clap about one month ago.  I guess you were looking at the latest tagged release, not the main branch?
> 
> https://github.com/joepio/atomic-data-rust/commit/0800e340b56d14b3cecaa035a456a86ccca83b5c

Oh, indeed.  Sorry if I wasted your time.  Would it perhaps make sense to issue tagged releases more frequently?

**Comment by joepio** [comment]
no worries!
Yeah, I should make it a more common process. I've set up most of the CI specifically to make it easy to publish a new version. Let's do it right now 💯
