### ISSUE TITLE
multiple async libraries used

### ISSUE THREAD

**Issue by jonassmedegaard** [joepio/atomic-data-rust#366]
It seems that `async-std`, and dependencies `async-global-executor`, `async-executor`, `async-mutex`, `async-io`, `async-lock`, `gloo-timers`, `kv-log-macro` and `wasm-bindgen-futures`, are used only at `server/src/handlers/upload.rs`.

Perhaps file size and compile time would improve if reusing some of the libraries used elsewhere in the code?

**Comment by joepio** [comment]
Good catch! It's completely unnecessary, as all calls use `.await` and none are actually async.

**Comment by jonassmedegaard** [comment]
You removed the *use* of `async-std` but still have it declared as a dependency in the `Cargo.toml` file.

**Comment by jonassmedegaard** [comment]
...but thanks for the swift fix!

**Comment by joepio** [comment]
whoops :')

**Comment by jonassmedegaard** [comment]
On my system that change reduced file size by 290kb, by no longer compiling in these 22 crates:
  * async-channel v1.6.1
  * async-executor v1.4.1
  * async-global-executor v2.0.3
  * async-io v1.6.0
  * async-lock v2.5.0
  * async-mutex v1.4.0
  * async-std v1.11.0
  * async-task v4.1.0
  * atomic-waker v1.0.0
  * blocking v1.1.0
  * cache-padded v1.1.1
  * concurrent-queue v1.2.2
  * ctor v0.1.12
  * event-listener v2.5.2
  * fastrand v1.4.0
  * futures-lite v1.12.0
  * kv-log-macro v1.0.7
  * parking v2.0.0
  * polling v2.2.0
  * socket2 v0.4.4
  * value-bag v1.0.0-alpha.8
  * waker-fn v1.1.0

:-)

**Comment by joepio** [comment]
Yay! 😁
